services:
  redmine-test:
    container_name: gp-redmine-test
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      REDMINE_DB_MYSQL: db # match service name "db"
      REDMINE_DB_DATABASE: redmine_test
      REDMINE_DB_USERNAME: root
      REDMINE_DB_PASSWORD: root
    volumes:
      - ./public/files-test:/usr/src/redmine/files
      - ./plugins:/app/plugins
      - ./themes:/usr/src/redmine/public/themes
      - ./config/database.yml:/usr/src/redmine/config/database.yml
    ports:
      - "3001:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: gp-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine_test
    volumes:
      - db_data:/var/lib/mysql
      - ./redmine_test_20260107.sql:/docker-entrypoint-initdb.d/01_redmine_test.sql:ro
    ports:
      - "3307:3306"

volumes:
  db_data:
