services:
  redmine:
    container_name: gp-redmine
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      REDMINE_DB_MYSQL: db # match service name "db"
      REDMINE_DB_DATABASE: redmine_test
      REDMINE_DB_USERNAME: root
      REDMINE_DB_PASSWORD: root
    volumes:
      - ./public/files-test:/app/files
      - ./plugins:/app/plugins
      - ./public/themes:/app/public/themes
      - ./config/database.yml:/app/config/database.yml
    ports:
      - "3001:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: gp-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine_test
    volumes:
      - db_data:/var/lib/mysql
      - ./redmine_test_20260107.sql:/docker-entrypoint-initdb.d/01_redmine_test.sql:ro
    ports:
      - "3307:3306"

  postgres:
    image: postgres:16
    container_name: gp-postgres
    environment:
      POSTGRES_DB: pruebaG
      POSTGRES_USER: gp
      POSTGRES_PASSWORD: "p455w0rd"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./00_create_postgres_role.sql:/docker-entrypoint-initdb.d/00_create_postgres_role.sql:ro
      - ./dump_1.sql:/docker-entrypoint-initdb.d/01_dump.sql:ro
    ports:
      - "5433:5432"

volumes:
  db_data:
  pg_data:
