production:
  adapter: mysql2
  database: redmine_prod2
  host: gp-mysql-prod2
  username: root
  password: rootie
  encoding: utf8
  port: 3306

development:
  adapter: mysql2
  database: redmine_prod2
  host: gp-mysql-prod2
  username: root
  password: rootie
  encoding: utf8
  port: 3306
